# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "DSPlab#"
description: > # this means to ignore newlines until "email:"
   Despair, Beer, Street Sign Destoryer, Wheel Developer

email: drsasimi@hotmail.com
#blog logo
logo: "/assets/images/blog_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Lee Sang Hyeon'
author: 'Lee Sang Hyeon'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://www.drsasimi.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@sigsegv11'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/sigsegv11
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/drsasimi
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
